clickhouse:
  outputs:
    dev:
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      port: 9000
      schema: sp600_stocks
      secure: false
      type: clickhouse
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      verify: false
  target: dev