clickhouse:
  outputs:
    dev:
      host: clickhouse
      password: ''
      port: 9000
      schema: sp600_stocks
      secure: false
      type: clickhouse
      user: default
      verify: false
  target: dev
